version: 0.2
 
phases:
  install:
    commands:
      - echo "No dependencies to install. This is just a test."
  build:
    commands:
      - echo "Running the build phase. (No actual build commands.)"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
