version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 18  # Change to match your project
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install  # Adjust for your project (e.g., mvn install for Java)
  build:
    commands:
      - echo Building the application...
      - npm run build  # Replace with your actual build command
  post_build:
    commands:
      - echo Build completed successfully.
 
artifacts:
  files:
    - '**/*'
