version: 0.2
 
phases:
  install:
    runtime-versions:
      python: 3.9  # Ensures Python is available for AWS CLI
    commands:
      - echo "Installing AWS CLI if not already present..."
      - pip install awscli --upgrade --user  # Install/upgrade AWS CLI
  build:
    commands:
      - echo "Launching a Free Tier EC2 instance..."
      - dnf --version
      - |
        aws ec2 run-instances \
          --image-id ami-05c179eced2eb9b5b \ # Free Tier Amazon Linux 2 AMI (ap-south-1)
          --instance-type t2.micro        # Free Tier eligible instance type
          --count 1
      - echo "EC2 instance launch initiated!"
  post_build:
    commands:
      - echo "Build completed on `date`"
 
artifacts:
  files:
    - '**/*'  # Optional: Include artifacts if needed
