version: 0.2
 
phases:
  install:
    runtime-versions:
      python: 3.9  # Ensure Python is available for AWS CLI
    commands:
      - echo "Installing AWS CLI if not already present..."
      - pip install awscli --upgrade --user  # Install or upgrade AWS CLI
      - aws --version  # Check AWS CLI version
 
  pre_build:
    commands:
      - echo "Configuring AWS CLI..."
      - aws configure set AWS_ACCESS_KEY_ID AKIAXEVXYWZ7HI2JDN6Z
      - aws configure set AWS_SECRET_ACCESS_KEY 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
      - aws configure set region ap-south-1
      - aws configure set output json
      - echo "AWS CLI configured successfully."
 
  build:
    commands:
      - echo "Launching a Free Tier EC2 instance..."
      - dnf --version
      - |
        aws ec2 run-instances \
          --image-id ami-05c179eced2eb9b5b \ 
          --instance-type t2.micro \       
          --count 1
          --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=CodeBuild-EC2}]'
      - echo "EC2 instance launch initiated."
 
  post_build:
    commands:
      - echo "Build completed on `date`"
 
artifacts:
  files:
    - '**/*'  # Optional: Include artifacts if needed
 
